### ISSUE TITLE
No git link on dockerhub page + no :latest tag

### ISSUE THREAD

**Issue by jamess60** [garybowers/iventoy_docker#1]
Hey Gary

Good effort with this image :)

Couple of pointers
1) there is no link to the git on the [dockerhub page](https://hub.docker.com/r/garybowers/iventoy), had to google it 
2) The latest image doesnt have a :latest tag so docker fails to pull without specifying :1.0.08

**Comment by garybowers** [comment]
Hey James, first off thanks so much for the feedback this is super awesome and useful!

1. I've thrown my github repo link everywhere :)
2. I've also added a latest tag

**Comment by jamess60** [comment]
Lovely stuff, cheers my man
